services:
  traefik:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - web-public
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      placement:
        constraints:
          - node.role==manager
    volumes:
      # Mount the Docker socket as read-only so Traefik can listen to events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certificates:/certificates
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
  php:
    image: ${SPIN_IMAGE_DOCKERFILE_PHP}
    environment:
      AUTORUN_ENABLED: "true" # ðŸ‘ˆ Remove this line if you don't want Laravel Automations
      AUTORUN_LARAVEL_MIGRATION: "true"
      APP_ENV: "${SPIN_DEPLOYMENT_ENVIRONMENT}"
      PHP_OPCACHE_ENABLE: "1"
      HEALTHCHECK_PATH: "/up"
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel-web.rule=Host(`${SPIN_APP_DOMAIN}`)"
        - "traefik.http.routers.laravel-web.entrypoints=websecure"
        - "traefik.http.routers.laravel-web.tls=true"
        - "traefik.http.routers.laravel-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.laravel-web.loadbalancer.server.port=8443"
        - "traefik.http.services.laravel-web.loadbalancer.server.scheme=https"
        # Health check
        - "traefik.http.services.laravel-web.loadbalancer.healthcheck.path=/up"
        - "traefik.http.services.laravel-web.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.laravel-web.loadbalancer.healthcheck.timeout=5s"
        - "traefik.http.services.laravel-web.loadbalancer.healthcheck.scheme=https"
  schedule:
    image: ${SPIN_IMAGE_DOCKERFILE_PHP}
    environment:
      APP_ENV: "${SPIN_DEPLOYMENT_ENVIRONMENT}"
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
  postgres:
    networks:
      - web-public
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_shared:/shared
  ssh:
    # We use an SSH image so we can securely tunnel into the Docker network with
    # tools like Sequel Pro, TablePlus, Sequel Ace, etc.
    # Learn more how to secure your tunnel here: https://github.com/serversideup/docker-ssh
    image: serversideup/docker-ssh:v3
    ports:
      - target: 2222
        published: 2222
        mode: host
    environment:
      # Be sure to set the authorized keys in the .env file or GitHub Actions secrets
      AUTHORIZED_KEYS: "${AUTHORIZED_KEYS}"
      # You can lock to a specific IP too (AllowUsers tunnel@1.2.3.4)
      ALLOWED_IPS: "AllowUsers tunnel"
    volumes:
      - tunnel_ssh_host_keys:/etc/ssh/ssh_host_keys
    networks:
      - web-public
  redis:
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - web-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
  horizon:
    image: ${SPIN_IMAGE_DOCKERFILE_PHP}
    environment:
      APP_ENV: "${SPIN_DEPLOYMENT_ENVIRONMENT}"
    stop_grace_period: 30s
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    deploy:
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: stop-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
  reverb:
    image: ${SPIN_IMAGE_DOCKERFILE_PHP}
    environment:
      APP_ENV: "${SPIN_DEPLOYMENT_ENVIRONMENT}"
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel-reverb.rule=Host(`${REVERB_HOST}`)"
        - "traefik.http.routers.laravel-reverb.entrypoints=websecure"
        - "traefik.http.routers.laravel-reverb.tls=true"
        - "traefik.http.routers.laravel-reverb.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.laravel-reverb.loadbalancer.server.port=8000"
        - "traefik.http.services.laravel-reverb.loadbalancer.server.scheme=http"

#  minio:
#    image: 'minio/minio:latest'
#    environment:
#      MINIO_ROOT_USER: '${MINIO_ADMIN_USER}'
#      MINIO_ROOT_PASSWORD: '${MINIO_ADMIN_PASSWORD}'
#      MINIO_DOMAIN: "media.${SPIN_APP_DOMAIN}"
#      MINIO_SERVER_URL: "https://media.${SPIN_APP_DOMAIN}"
#      MINIO_BROWSER_REDIRECT_URL: "https://console.media.${SPIN_APP_DOMAIN}"
#    volumes:
#      - "storage_minio:/data/minio"
#    command: minio server /data/minio --console-address ":8900"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      web-public:
#        aliases: ["minio"]
#    deploy:
#      restart_policy:
#        delay: 10s
#        max_attempts: 10
#        window: 60s
#      labels:
#        - "traefik.enable=true"
#        # API
#        - "traefik.http.routers.minio.rule=Host(`media.${SPIN_APP_DOMAIN}`)"
#        - "traefik.http.routers.minio.entrypoints=websecure"
#        - "traefik.http.routers.minio.tls=true"
#        - "traefik.http.routers.minio.service=minio"
#        - "traefik.http.services.minio.loadbalancer.server.port=9000"
#        # Console
#        - "traefik.http.routers.minio-console.rule=Host(`console.media.${SPIN_APP_DOMAIN}`)"
#        - "traefik.http.routers.minio-console.entrypoints=websecure"
#        - "traefik.http.routers.minio-console.tls=true"
#        - "traefik.http.routers.minio-console.service=minio-console"
#        - "traefik.http.services.minio-console.loadbalancer.server.port=8900"
#  minio-user-init:
#    image: serversideup/minio-user-init:latest
#    depends_on:
#      - minio
#    environment:
#      MINIO_ADMIN_USER: "${MINIO_ADMIN_USER}"
#      MINIO_ADMIN_PASSWORD: "${MINIO_ADMIN_PASSWORD}"
#      MINIO_ALIAS: "myminio"
#      MINIO_HOST: "https://media.${SPIN_APP_DOMAIN}:9000"
#      MINIO_USER_ACCESS_KEY: "${MINIO_USER_ACCESS_KEY}"
#      MINIO_USER_SECRET_KEY: "${MINIO_USER_SECRET_KEY}"
#      MINIO_USER_BUCKET: "media"
#      MINIO_USER_BUCKET_PERMISSIONS: "s3:ListBucket,s3:GetBucketLocation"
#      MINIO_USER_OBJECT_PERMISSIONS: "s3:PutObject,s3:GetObject"
#    networks:
#      - web-public
#    deploy:
#      restart_policy:
#        condition: none
#      placement:
#        constraints:
#          - node.role == manager
#      replicas: 1
#      update_config:
#        order: stop-first

configs:
  traefik:
    name: "traefik-${SPIN_MD5_HASH_TRAEFIK_YML}.yml"
    file: ./.infrastructure/conf/traefik/prod/traefik.yml
volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  postgres_data:
  postgres_shared:
  tunnel_ssh_host_keys:
  redis_data:
  storage_minio:
networks:
  web-public:
