services:
  php:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
    depends_on:
      - postgres
  node:
    build:
      target: ci
      dockerfile: Dockerfile.node
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
  mailpit:
    image: axllent/mailpit
  schedule:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
  postgres:
    volumes:
      - './.infrastructure/conf/database/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    environment:
      POSTGRES_DB: "laravel"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
  horizon:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
  reverb:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
